# Generated by Django 5.0 on 2024-06-30 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='formulario',
            new_name='contacto',
        ),
    ]
